#%RAML 1.0 DocumentationItem
  title: Introduction
  content: |
   
    # Innovation Layer / Bi-Modal
    Web API facade on to Alainn's SOA Architecture. Designed to be the central point of access to all business process level SOAP services.
    
    # Resource Hierarchy
    
    The resources are in part independent of the user browsing them
    
    * /items
    * /brands
    
    Others are personal to the authenticated User: 
    
    * /basket
    * /wish-list
    
    All return application/json as Response media-type and all accept only application/json as request media-type.
    
    # Hypermedia
    
    The usual form of each response is to include a links array with a number of objects of the form:
    
    **href**: the url
    
    **rel**:  the meaning of the url (Image, prev, next, self, etc.)
    
    **label**: UI label
    
    ```json
        "links": [
            {
                "href": "https://alainn-omni-channel-api.cloudhub.io/v1.0?pageIndex=28&pageSize=7",
                "rel": "next"
            },
            {
                "href": "https://alainn-omni-channel-api.cloudhub.io/v1.0?pageIndex=14&pageSize=7",
                "rel": "prev"
            },
            {
                "href": "https://alainn-omni-channel-api.cloudhub.io/v1.0/items",
                "rel": "self"
            }
        ]
    ```
    
    If the response is a collection object, it will have a links array at the root and for each item in the items array.
    
    ```json
      "collection": {
        "size": 7,
        "items": [
          {
              "id": "B003Y60XCC",
              "type": "Chemical Hair Dyes",
              "name": "L'Oreal Oreor 30 Volume Creme Developer",
              "summary": "Fully stabilized formula - Freshness assured",
              "brand": "L'Oreal Paris",
              "links": [
                  {
                      "href": "https://alainn-omni-channel-api.cloudhub.io/v1.0/items/B003Y60XCC",
                      "rel": "self"
                  },
                  {
                      "href": "http://ecx.images-amazon.com/images/I/41MWX6KNAuL._SL75_.jpg",
                      "rel": "SmallImage"
                  }
              ]
          },
          { ...
    ```
    
    # API Manager
    
    Registered both as a Service with the OAuth 2.0 Access Token Enforcement policy applied, and also as a Consumer of 
    
    * Item Service
    * Customer Service
    * Basket Service
    * WishList Service
    * Order-fulfillment Service
    * Registration Service 
    * Point-of-Sale Service