#%RAML 1.0 DocumentationItem
  title: Security
  content: |
    # Policy
    
    Though the API does not implement any authentication / authorisation logic itself, it is dependent on the user details which the Ping Federate Token enforcement policy leaves in context so as to correlate the personal calls mentioned in the section on Resource Hierarchy above. 